image: gitpod/workspace-full-vnc:2024-05-27-17-11-15
tasks:
  - name: Configure shell
    before: bash scripts/profile.sh ; exit
  - name: Install Nextflow
    before: |
      curl -s https://get.nextflow.io | bash
      chmod +x nextflow
      mkdir -p ~/.local/bin
      mv nextflow ~/.local/bin
      exit
  - name: Install packages
    before: |
      sudo apt update
      sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils libxcb-cursor0 libopengl0 libegl1-mesa mousepad
      exit
  - name: Install python packages
    before: |
      pip install napari[all] notebook pandas matplotlib
      exit
  - name: Download exemplar-002
    init: |
      cd $GITPOD_REPO_ROOT
      mkdir -p exemplar-002
      cd exemplar-002
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-03.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-04.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-05.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-03-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-03-ffp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-04-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-04-ffp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-05-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-05-ffp.tif &
      wait
      exit
  - name: Terminal
    command: clear; bash

ports:
  - port: 6080
    description: Remote desktop access
    onOpen: ignore
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
