image: gitpod/workspace-full-vnc:2024-05-27-17-11-15
tasks:
  - name: Configure shell
    init: |
      cat << EOF > ~/.bashrc.d/00-cwd
      test -e "$GITPOD_REPO_ROOT" && cd "$GITPOD_REPO_ROOT"
      EOF
  - name: Install Nextflow
    init: |
      curl -s https://get.nextflow.io | bash
      chmod +x nextflow
      mkdir -p ~/.local/bin
      mv nextflow ~/.local/bin
      exit
  - name: Install packages
    init: |
      sudo apt update
      sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils libxcb-cursor0 libopengl0 libegl1-mesa
      exit
  - name: Install Napari and Jupyter
    init: |
      pip install napari[all] notebook
      exit
  - name: Download exemplar-002
    init: |
      cd $GITPOD_REPO_ROOT
      mkdir -p exemplar-002
      cd exemplar-002
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-03.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-04.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/raw/exemplar-002-cycle-05.ome.tiff &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-03-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-03-ffp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-04-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-04-ffp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-05-dfp.tif &
      curl -O https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/illumination/exemplar-002-cycle-05-ffp.tif &
      wait
      exit
  - name: Terminal
    command: clear; bash

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 8888
    onOpen: ignore

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
